# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aa4ad4d6757ca49831ab70dfa066faf42e2f5041b0348a9cc273cf2e73a6b3311f97a0ec1c88485966ef49f815686f903fa7eace28308e2128ee1e9fa8cd98b0

test:
  secret_key_base: 3db86bc1fbe384042d4f0a325a535b0a45d11e08ecba884146de22aa6ee347e94a74a39dd204a3e14decfd7140979b3b55807e82a9ed710068e983de5d85a8bb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
